// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNVSKJ-Je8SrJELTlyF53SUot5HLNcbNI',
    appId: '1:982409964349:web:427aedcd5311bee6d57354',
    messagingSenderId: '982409964349',
    projectId: 'instagram-lpkl-a5317',
    authDomain: 'instagram-lpkl-a5317.firebaseapp.com',
    storageBucket: 'instagram-lpkl-a5317.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDutm3coykZ62i3Vv0mVTsvihdjln_zUqA',
    appId: '1:982409964349:android:5463be0c88e4787dd57354',
    messagingSenderId: '982409964349',
    projectId: 'instagram-lpkl-a5317',
    storageBucket: 'instagram-lpkl-a5317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOrFyJNZCJNT4A4A9pXckMKxYcAN_qfpE',
    appId: '1:982409964349:ios:2127c1dc36e4b738d57354',
    messagingSenderId: '982409964349',
    projectId: 'instagram-lpkl-a5317',
    storageBucket: 'instagram-lpkl-a5317.appspot.com',
    iosBundleId: 'com.example.instagramLpkl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOrFyJNZCJNT4A4A9pXckMKxYcAN_qfpE',
    appId: '1:982409964349:ios:a5139e7c9b6c8c9fd57354',
    messagingSenderId: '982409964349',
    projectId: 'instagram-lpkl-a5317',
    storageBucket: 'instagram-lpkl-a5317.appspot.com',
    iosBundleId: 'com.example.instagramLpkl.RunnerTests',
  );
}
